#!/usr/bin/env python3
import os
import sys
import subprocess
import re
import argparse
import glob


def run_cmd(cmd, ignore_error=False):
    print(f"[*] 执行命令: {cmd}")
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )
        if result.stdout.strip():
            print(f"    输出: {result.stdout.strip()}")
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"\n[!] 严重错误: 命令执行失败 -> '{cmd}'")
        print(f"    返回状态码: {e.returncode}")
        print(f"    错误日志详情:\n{e.output}")
        if not ignore_error:
            print("[-] 流程已终止。")
            sys.exit(1)
        else:
            print("[*] 已忽略此错误，继续执行后续步骤。")
            return None


def get_wdm_device():
    devices = glob.glob('/dev/cdc-wdm*')
    if not devices:
        print("[!] 致命错误: 未能在 /dev/ 目录下找到 cdc-wdm 设备。请检查模块是否正确连接。")
        sys.exit(1)
    devices.sort()
    device = devices[0]
    print(f"[+] 找到控制设备: {device}")
    return device


def get_wwan_interface():
    try:
        interfaces = os.listdir('/sys/class/net/')
        for iface in interfaces:
            if iface.startswith('ww'):
                print(f"[+] 找到数据网卡: {iface}")
                return iface
        print("[!] 致命错误: 未能在 /sys/class/net/ 找到以 'ww' 开头的网卡接口。")
        sys.exit(1)
    except FileNotFoundError:
        print("[!] 致命错误: 无法读取网卡列表。")
        sys.exit(1)


def extract_and_apply_dns(wdm_device):
    print("[*] 正在向模块查询当前网络设置...")
    output = run_cmd(f"qmicli -d {wdm_device} --wds-get-current-settings")
    dns_servers = re.findall(
        r'IPv4 (?:primary|secondary) DNS:\s*([\d\.]+)', output)  # type: ignore
    if not dns_servers:
        print("[!] 错误: 未能在 qmicli 输出中找到 IPv4 DNS 地址。")
        print("    可能是拨号未完全成功，或者网络不支持。")
        sys.exit(1)
    print(f"[+] 成功提取到 DNS: {', '.join(dns_servers)}")
    try:
        with open('/etc/resolv.conf', 'w') as f:
            f.write("# Generated by qmi_manager.py\n")
            for dns in dns_servers:
                f.write(f"nameserver {dns}\n")
        print("[+] 成功将 DNS 配置写入 /etc/resolv.conf")
    except IOError as e:
        print(f"[!] 写入 /etc/resolv.conf 失败: {e}")
        sys.exit(1)


def start_network():
    print("=== 开始初始化网络 (start_network) ===")
    wdm_device = get_wdm_device()
    wwan_iface = get_wwan_interface()
    run_cmd(f"ip link set {wwan_iface} down")
    run_cmd(f"echo 'Y' > /sys/class/net/{wwan_iface}/qmi/raw_ip")
    run_cmd(f"qmi-network {wdm_device} start")
    run_cmd(f"ip link set {wwan_iface} up")
    run_cmd(f"udhcpc -q -f -i {wwan_iface}")
    extract_and_apply_dns(wdm_device)
    print("\n[✔] 启动流程全部成功完成！目前模块已连通网络。")


def stop_network():
    print("=== 开始断开网络 (stop_network) ===")
    wdm_device = get_wdm_device()
    wwan_iface = get_wwan_interface()
    run_cmd(f"ip link set {wwan_iface} down")
    run_cmd(f"qmi-network {wdm_device} stop", ignore_error=True)
    print("\n[✔] 停止流程执行完毕，网络已断开。")


if __name__ == "__main__":
    if os.geteuid() != 0:
        print("[!] 权限拒绝: 本脚本必须使用 sudo 或 root 权限运行。")
        sys.exit(1)
    parser = argparse.ArgumentParser(description="Quectel QMI 模块网络自动化管理脚本")
    parser.add_argument("action", choices=[
                        "up", "down"], help="执行的操作: up 或 down")
    args = parser.parse_args()
    if args.action == "up":
        start_network()
    elif args.action == "down":
        stop_network()
